option corrige du script qtex2pdf

diff --git a/bin/qtex2pdf b/bin/qtex2pdf
--- a/bin/qtex2pdf
+++ b/bin/qtex2pdf
@@ -1,14 +1,35 @@
 #!/bin/bash
-qtex=$1
-[ -z "$qtex" ] && echo "Usage: $0 <input_qtex_file>" && exit 1
-QTEX_SRC="/home/filipe/dev/qtex/src"
-QTEX_TESTS="/home/filipe/dev/qtex/tests"
-build="$QTEX_TESTS/build"
-mkdir -p "$build"
-template="$QTEX_SRC/qtex/qtex2latex/templates/template_qcm_simple.tex"
-[ ! -f "$template" ] && echo "Template not found" && exit 1
-cat ${template} > ${build}/tmp_simple.tex
-qtex2latex -i ${qtex} >> $build/tmp_simple.tex
-echo "\end{document}" >> $build/tmp_simple.tex
-pdflatex -output-directory $build $build/tmp_simple.tex > "$build/pdflatex.log" 2>&1 
-mupdf -r 216 $build/tmp_simple.pdf #2> /dev/null &
+usage()
+{
+    echo "Usage: $0 [-c] <input_qtex_file>" 
+    exit 1
+}
+if [ $# -eq 2 ] 
+then
+    CORRIGE=$1
+    QTEX=$2
+    [ $CORRIGE != "-c" ] && usage 
+else
+    QTEX=$1
+fi
+[ -z "$QTEX" ] && [ ! -f "$QTEX" ] && usage
+QTEX_ROOT="/home/filipe/dev/qtex/"
+QTEX_SRC="$QTEX_ROOT/src"
+QTEX_TESTS="$QTEX_ROOT/tests"
+TEMPLATE="$QTEX_SRC/qtex/qtex2latex/templates/template_qcm_simple.tex"
+BUILD="$QTEX_TESTS/build"
+TEX_OUTPUT=${BUILD}/tmp_simple.tex
+PDF_OUTPUT=${BUILD}/tmp_simple.pdf
+LOG_OUTPUT=${BUILD}/pdflatex.log
+mkdir -p "$BUILD"
+[ ! -f "$TEMPLATE" ] && echo "Template not found" && exit 1
+cat ${TEMPLATE} > $TEX_OUTPUT
+if [ -z $CORRIGE ] 
+then 
+    qtex2latex -i ${QTEX} >> $TEX_OUTPUT
+else
+    qtex2latex --corrige -i ${QTEX} >> $TEX_OUTPUT
+fi
+echo "\end{document}" >> $TEX_OUTPUT 
+pdflatex -output-directory $BUILD $TEX_OUTPUT > $LOG_OUTPUT 2>&1 
+mupdf -r 216 $PDF_OUTPUT 2> /dev/null & 
